version: '3' # docker version
services: 
  www:
    image: php:apache
    volumes: 
      - "./:/var/www/html" # синхронизация каталога преокта в веб каталогом контейнера
    ports:
      - 86:80
      - 443:433 #для ssl трафика
  db:
    image: mysql:latest
    environment:
      - MYSQL_DATABASE=php_docker
      - MYSQL_USER=php_docker
      - MYSQL_PASSWORD=password
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
    volumes:
      - "./db:/docker-entrypoint-initdb.d" # this is how we persist a sql db even when container stops
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8001:80
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306